services:
  minecraft:
    build: docker
    image: minecraft-server:latest
    container_name: minecraft-server
    ports:
      - 1337:1337
    volumes:
      - minecraft-server-world:/opt/minecraft-server/world

volumes:
  minecraft-server-world:
    name: minecraft-server-world