services:
  minecraft:
    image: minecraft-server:v1.0.0
    container_name: minecraft-server
    ports:
      - 1337:1337
    volumes:
      - minecraft-server-world:/opt/minecraft-server/world
      - type: bind
        source: ./server.properties
        target: /opt/minecraft-server/world/server.properties

volumes:
  minecraft-server-world:
    name: minecraft-server-world