services:
  minecraft:
    build: .
    image: minecraft-server:latest
    container_name: minecraft-server
    ports:
      - 1337:1337
    volumes:
      - type: bind
        source: ./server.properties
        target: /opt/minecraft-server/server.properties
      - minecraft-server-world:/opt/minecraft-server/world

volumes:
  minecraft-server-world:
    name: minecraft-server-world